# Generated by Django 4.2.16 on 2024-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
